spring:
  application:
    name: review
  datasource:
    url: jdbc:mysql://localhost:3306/class30
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

